### ISSUE TITLE
Ouput version number whenever there `sinix` command executes

### ISSUE THREAD

**Issue by sanket143** [sinix-dev/sinix.js#12]
**Note:** This issue is reserved for SLoP Contributors.

The output should be in the following format.
```
$ npm run sinix build
sinix.js v0.1

// output from build command
```

**Comment by Devansu-Yadav** [comment]
Hi, can I try and work on this?

**Comment by janvig** [comment]
Yes, you can.

**Comment by Devansu-Yadav** [comment]
@sanket143 @janvig Do I push the files that were modified while working on this issue or a Screenshot of the output is fine?

**Comment by sanket143** [comment]
@Devansu-Yadav Yes, you need to commit the modified files and push to your forked repo branch. You don't need to put screenshot, just raise a PR with the required changes.
