### ISSUE TITLE
Enable eslint in channel/index.js

### ISSUE THREAD

**Issue by janvig** [sinix-dev/sinix.js#9]

**Comment by AnirudhPanda** [comment]
Hey @janvig can you please provide me more details about this issue?

**Comment by janvig** [comment]
@AnirudhPanda ESLint is currently disabled in https://www.github.com/sinix-dev/sinix.js/tree/master/channel%2Findex.js
You just need to enable it.

**Comment by AnirudhPanda** [comment]
Actually I just learnt about eslint.
By removing the comment at the top of the index.js file, eslint will be enabled?

**Comment by janvig** [comment]
Yes, you can validate that too by running `$ npm run lint`.
Glad you looked through it.

**Comment by AnirudhPanda** [comment]
> Yes, you can validate that too by running `$ npm run lint`.
> Glad you looked through it.

`npm run lint` worked after I installed eslint globally and also in local but it also modified package.json and package-lock.json.
Should I continue with it?

**Comment by janvig** [comment]
Great! Create a pull request so that I can look into it.
